apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongo-depl
spec:
  replicas: 1 #This tells the k8s to run 1 replica of this deployment
  selector:
    matchLabels:
      app: tickets-mongo #label that is going to used to match the pods
  template:
    metadata:
      labels:
        app: tickets-mongo #label that is going to applied for the pods
    spec:
      containers:
        - name: tickets-mongo #name of the container
          image: mongo #From the official mongo image in docker hub

---
#ClusterIP service for the auth-mongo deployment
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
spec:
  type: ClusterIP #This service is only accessible within the cluster
  selector:
    app: tickets-mongo #label that is going to used to match the pods
  ports:
    - name: db
      protocol: TCP
      #Default port for MongoDB is 27017
      port: 27017 #port that the service is going to listen on
      targetPort: 27017 #port that the container is going to listen on
